### ISSUE TITLE
Update documentation to account for Apple Silicon users

### ISSUE THREAD

**Issue by aromberg** [TRON-Bioinformatics/neofox#10]
Hi all,

to save Apple Silicon users (like me!) some time, I think it would be great to add `docker build --platform linux/amd64 --tag neofox-docker .` to the [installation page](https://neofox.readthedocs.io/en/latest/02_installation.html).

Getting NeoFox to run on M1 seem to be possible to some extend by using `python:3.7` instead of `python:3.7-slim` (includes gcc) and installing `cython` before building and installing NeoFox. Unfortunately, the process still fails when running `neofox-configure` since `netMHCpan-4.1` is missing arm binaries.

**Comment by priesgo** [comment]
Thanks for the feedback @aromberg this is now in develop branch ready for the next release
